// Comprehensive country list with ISO currency codes. Bundled (not fetched at
// runtime) so it's always available; live FX rates convert prices day-to-day.
export type Country = { code: string; name: string; currency: string };

export const COUNTRIES: Country[] = [
  { code: "PK", name: "Pakistan", currency: "PKR" },
  { code: "IN", name: "India", currency: "INR" },
  { code: "BD", name: "Bangladesh", currency: "BDT" },
  { code: "LK", name: "Sri Lanka", currency: "LKR" },
  { code: "NP", name: "Nepal", currency: "NPR" },
  { code: "BT", name: "Bhutan", currency: "BTN" },
  { code: "MV", name: "Maldives", currency: "MVR" },
  { code: "AF", name: "Afghanistan", currency: "AFN" },
  { code: "AU", name: "Australia", currency: "AUD" },
  { code: "NZ", name: "New Zealand", currency: "NZD" },
  { code: "US", name: "United States", currency: "USD" },
  { code: "CA", name: "Canada", currency: "CAD" },
  { code: "GB", name: "United Kingdom", currency: "GBP" },
  { code: "IE", name: "Ireland", currency: "EUR" },
  { code: "AE", name: "United Arab Emirates", currency: "AED" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR" },
  { code: "QA", name: "Qatar", currency: "QAR" },
  { code: "KW", name: "Kuwait", currency: "KWD" },
  { code: "BH", name: "Bahrain", currency: "BHD" },
  { code: "OM", name: "Oman", currency: "OMR" },
  { code: "JO", name: "Jordan", currency: "JOD" },
  { code: "LB", name: "Lebanon", currency: "LBP" },
  { code: "IQ", name: "Iraq", currency: "IQD" },
  { code: "IR", name: "Iran", currency: "IRR" },
  { code: "IL", name: "Israel", currency: "ILS" },
  { code: "PS", name: "Palestine", currency: "ILS" },
  { code: "TR", name: "Turkey", currency: "TRY" },
  { code: "EG", name: "Egypt", currency: "EGP" },
  { code: "MA", name: "Morocco", currency: "MAD" },
  { code: "DZ", name: "Algeria", currency: "DZD" },
  { code: "TN", name: "Tunisia", currency: "TND" },
  { code: "LY", name: "Libya", currency: "LYD" },
  { code: "SD", name: "Sudan", currency: "SDG" },
  { code: "ZA", name: "South Africa", currency: "ZAR" },
  { code: "NG", name: "Nigeria", currency: "NGN" },
  { code: "KE", name: "Kenya", currency: "KES" },
  { code: "GH", name: "Ghana", currency: "GHS" },
  { code: "TZ", name: "Tanzania", currency: "TZS" },
  { code: "UG", name: "Uganda", currency: "UGX" },
  { code: "ET", name: "Ethiopia", currency: "ETB" },
  { code: "RW", name: "Rwanda", currency: "RWF" },
  { code: "SN", name: "Senegal", currency: "XOF" },
  { code: "CI", name: "Côte d'Ivoire", currency: "XOF" },
  { code: "CM", name: "Cameroon", currency: "XAF" },
  { code: "ZM", name: "Zambia", currency: "ZMW" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL" },
  { code: "DE", name: "Germany", currency: "EUR" },
  { code: "FR", name: "France", currency: "EUR" },
  { code: "IT", name: "Italy", currency: "EUR" },
  { code: "ES", name: "Spain", currency: "EUR" },
  { code: "PT", name: "Portugal", currency: "EUR" },
  { code: "NL", name: "Netherlands", currency: "EUR" },
  { code: "BE", name: "Belgium", currency: "EUR" },
  { code: "AT", name: "Austria", currency: "EUR" },
  { code: "GR", name: "Greece", currency: "EUR" },
  { code: "FI", name: "Finland", currency: "EUR" },
  { code: "LU", name: "Luxembourg", currency: "EUR" },
  { code: "CY", name: "Cyprus", currency: "EUR" },
  { code: "MT", name: "Malta", currency: "EUR" },
  { code: "CH", name: "Switzerland", currency: "CHF" },
  { code: "SE", name: "Sweden", currency: "SEK" },
  { code: "NO", name: "Norway", currency: "NOK" },
  { code: "DK", name: "Denmark", currency: "DKK" },
  { code: "IS", name: "Iceland", currency: "ISK" },
  { code: "PL", name: "Poland", currency: "PLN" },
  { code: "CZ", name: "Czechia", currency: "CZK" },
  { code: "SK", name: "Slovakia", currency: "EUR" },
  { code: "HU", name: "Hungary", currency: "HUF" },
  { code: "RO", name: "Romania", currency: "RON" },
  { code: "BG", name: "Bulgaria", currency: "BGN" },
  { code: "HR", name: "Croatia", currency: "EUR" },
  { code: "SI", name: "Slovenia", currency: "EUR" },
  { code: "RS", name: "Serbia", currency: "RSD" },
  { code: "UA", name: "Ukraine", currency: "UAH" },
  { code: "RU", name: "Russia", currency: "RUB" },
  { code: "BY", name: "Belarus", currency: "BYN" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN" },
  { code: "GE", name: "Georgia", currency: "GEL" },
  { code: "AM", name: "Armenia", currency: "AMD" },
  { code: "CN", name: "China", currency: "CNY" },
  { code: "HK", name: "Hong Kong", currency: "HKD" },
  { code: "TW", name: "Taiwan", currency: "TWD" },
  { code: "JP", name: "Japan", currency: "JPY" },
  { code: "KR", name: "South Korea", currency: "KRW" },
  { code: "SG", name: "Singapore", currency: "SGD" },
  { code: "MY", name: "Malaysia", currency: "MYR" },
  { code: "ID", name: "Indonesia", currency: "IDR" },
  { code: "TH", name: "Thailand", currency: "THB" },
  { code: "VN", name: "Vietnam", currency: "VND" },
  { code: "PH", name: "Philippines", currency: "PHP" },
  { code: "MM", name: "Myanmar", currency: "MMK" },
  { code: "KH", name: "Cambodia", currency: "KHR" },
  { code: "LA", name: "Laos", currency: "LAK" },
  { code: "BR", name: "Brazil", currency: "BRL" },
  { code: "MX", name: "Mexico", currency: "MXN" },
  { code: "AR", name: "Argentina", currency: "ARS" },
  { code: "CL", name: "Chile", currency: "CLP" },
  { code: "CO", name: "Colombia", currency: "COP" },
  { code: "PE", name: "Peru", currency: "PEN" },
  { code: "VE", name: "Venezuela", currency: "VES" },
  { code: "EC", name: "Ecuador", currency: "USD" },
  { code: "UY", name: "Uruguay", currency: "UYU" },
  { code: "BO", name: "Bolivia", currency: "BOB" },
  { code: "PY", name: "Paraguay", currency: "PYG" },
  { code: "CR", name: "Costa Rica", currency: "CRC" },
  { code: "PA", name: "Panama", currency: "USD" },
];

// PK 🇵🇰 — regional-indicator flag from the 2-letter code
export function flagEmoji(code: string) {
  return code
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

export function countryName(code: string) {
  return COUNTRIES.find((c) => c.code === code)?.name ?? code;
}

export function currencyForCountry(code: string): string | null {
  return COUNTRIES.find((c) => c.code === code)?.currency ?? null;
}
